# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Node.js app to Azure Web App - webyatri

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read # This is required for actions/checkout

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '22.x'

      - name: Install serve, dependencies and build app
        run: |
          npm install -g serve
          npm install
          npm run build

      - name: Zip build artifact for deployment
        run: zip -r release.zip build

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: react-app-build
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write # This is required for requesting the JWT
      contents: read  # This is required for actions/checkout

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: react-app-build

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_93DE891C89044699A89008AA9D14C58F }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_5328093716EE46C5881994FA0D993ABA }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_0647691726FA4DA185F08B082034B459 }}

      - name: Deploy to Azure Web App with startup command
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'webyatri'
          slot-name: 'Production'
          package: release.zip
          startup-file: 'npx serve -s build'
